Document: libmsgbuff
Title: Debian libmsgbuff Manual
Author: <insert document author here>
Abstract: This manual describes what libmsgbuff is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libmsgbuff/libmsgbuff.sgml.gz

Format: postscript
Files: /usr/share/doc/libmsgbuff/libmsgbuff.ps.gz

Format: text
Files: /usr/share/doc/libmsgbuff/libmsgbuff.text.gz

Format: HTML
Index: /usr/share/doc/libmsgbuff/html/index.html
Files: /usr/share/doc/libmsgbuff/html/*.html
